FORMULA_SHEET = {
    "Calculus": [
        "d/dx[xⁿ] = nxⁿ⁻¹",
        "d/dx[eˣ] = eˣ",
        "d/dx[ln x] = 1/x",
        "d/dx[sin x] = cos x",
        "d/dx[cos x] = -sin x",
        "Chain Rule: d/dx[f(g(x))] = f'(g(x))·g'(x)",
        "Product: d/dx[uv] = u'v + uv'",
        "Quotient: d/dx[u/v] = (u'v - uv')/v²",
        "∫xⁿdx = xⁿ⁺¹/(n+1) + C",
        "∫eˣdx = eˣ + C",
        "∫(1/x)dx = ln|x| + C",
        "∫sin x dx = -cos x + C",
        "∫cos x dx = sin x + C",
        "IBP: ∫u dv = uv - ∫v du",
    ],
    "Algebra": [
        "Quadratic: x = (-b ± √(b²-4ac)) / 2a",
        "(a+b)² = a² + 2ab + b²",
        "(a-b)² = a² - 2ab + b²",
        "(a+b)(a-b) = a² - b²",
        "aⁿ · aᵐ = aⁿ⁺ᵐ",
        "log(ab) = log a + log b",
        "log(a/b) = log a - log b",
        "log(aⁿ) = n·log a",
        "Change of base: logₐb = log b / log a",
    ],
    "Statistics": [
        "Mean: μ = Σx / n",
        "Variance: σ² = Σ(x-μ)² / n",
        "Std Dev: σ = √(σ²)",
        "Z-score: z = (x - μ) / σ",
        "P(A∪B) = P(A) + P(B) - P(A∩B)",
        "Bayes: P(A|B) = P(B|A)·P(A) / P(B)",
        "Binomial: P(X=k) = C(n,k)·pᵏ·(1-p)ⁿ⁻ᵏ",
        "Correlation r = Σ(x-x̄)(y-ȳ) / √[Σ(x-x̄)²·Σ(y-ȳ)²]",
    ],
    "Optimization": [
        "Critical point: ∇f(x) = 0",
        "Hessian: H = ∂²f/∂xᵢ∂xⱼ",
        "Min if H positive definite",
        "Max if H negative definite",
        "Lagrange: ∇f = λ∇g",
        "KKT: ∇f = Σλᵢ∇gᵢ,  λᵢgᵢ=0,  λᵢ≥0",
        "Gradient Descent: xₙ₊₁ = xₙ - α∇f(xₙ)",
    ],
    "Fuzzy Set Theory": [
        "Union: μ_A∪B = max(μA, μB)",
        "Intersection: μ_A∩B = min(μA, μB)",
        "Complement: μ_Ā = 1 - μA",
        "Algebraic Product: μA · μB",
        "Algebraic Sum: μA + μB - μA·μB",
        "Alpha-cut: Aα = {x | μA(x) ≥ α}",
        "Centroid: x* = ∫x·μ(x)dx / ∫μ(x)dx",
    ],
    "Linear Algebra": [
        "det(AB) = det(A)·det(B)",
        "(AB)⁻¹ = B⁻¹A⁻¹",
        "Eigenvalue: Av = λv  →  det(A-λI) = 0",
        "Rank-Nullity: rank(A) + null(A) = n",
        "Norm: ‖v‖ = √(Σvᵢ²)",
        "Dot product: a·b = ‖a‖‖b‖cos θ",
    ],
}
